# Generated by Django 5.0.7 on 2024-07-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.PositiveBigIntegerField()),
                ('meter_code', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
            ],
        ),
    ]
