# Generated by Django 5.0.7 on 2024-07-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiSmart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meter',
            options={'managed': False},
        ),
    ]
