# Generated by Django 5.0.7 on 2024-07-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiSmart', '0002_alter_meter_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meter',
            table='smart_med.stg4_medidores',
        ),
    ]
