# Generated by Django 4.1 on 2024-11-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSmart', '0003_alter_meter_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('alarm_pk', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('alarm_id', models.CharField(max_length=25)),
                ('meter_code', models.CharField(max_length=25)),
                ('alarm_time_id', models.IntegerField()),
                ('alarm_timestamp_id', models.IntegerField()),
                ('recv_time_id', models.IntegerField()),
                ('recv_timestamp_id', models.IntegerField()),
            ],
            options={
                'db_table': 'smart_med"."final_alarmas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_id', models.CharField(max_length=255)),
                ('online_status', models.IntegerField()),
                ('last_update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'as_equip_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('falla_id', models.IntegerField(primary_key=True, serialize=False)),
                ('falla_desc', models.CharField(max_length=255)),
                ('falla_type', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'smart_med"."final_fallas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('gateway_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('status', models.CharField(max_length=30)),
                ('service_center', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'smart_med"."stg3_gateways',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hechos',
            fields=[
                ('lectura_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gateway_id', models.CharField(max_length=20)),
                ('eui', models.CharField(max_length=20)),
                ('meter_id', models.CharField(max_length=20)),
                ('real_volume', models.DecimalField(decimal_places=3, max_digits=20)),
                ('recv_time_id', models.IntegerField()),
                ('recv_ts_id', models.IntegerField()),
                ('meter_time', models.IntegerField()),
            ],
            options={
                'db_table': 'smart_med"."final_hechos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('incidencia_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('meter_code', models.CharField(max_length=25)),
                ('fecha_incidencia', models.DateTimeField()),
                ('img', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'smart_med"."final_incidencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tapa',
            fields=[
                ('tapa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tapa_desc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'smart_med"."final_tapas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaCombinada',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('meter_code', models.CharField(max_length=60)),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'smart_med"."mi_vista_combinada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatusLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('equip_id', models.CharField(max_length=255)),
                ('status_time', models.DateTimeField()),
                ('online_status', models.BooleanField()),
            ],
            options={
                'db_table': 'as_equip_status_logs',
            },
        ),
        migrations.AlterModelTable(
            name='meter',
            table='smart_med"."final_medidores',
        ),
    ]
