# Generated by Django 4.1 on 2025-02-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSmart', '0005_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='user_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
