# Generated by Django 4.1 on 2025-05-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiSmart", "0006_description_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalHechos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway_id", models.CharField(blank=True, max_length=16, null=True)),
                ("eui", models.CharField(blank=True, max_length=16, null=True)),
                ("meter_id", models.CharField(db_index=True, max_length=16)),
                (
                    "real_volume",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                ("recv_time_id", models.IntegerField(db_index=True)),
                ("recv_ts_id", models.IntegerField(blank=True, null=True)),
                ("dept_code", models.CharField(blank=True, max_length=11, null=True)),
                ("seq", models.BigIntegerField(blank=True, null=True)),
                (
                    "freq",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=11, null=True
                    ),
                ),
                ("sf", models.CharField(blank=True, max_length=16, null=True)),
                ("rssi", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "lnsr",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=11, null=True
                    ),
                ),
                ("meter_time", models.IntegerField(blank=True, null=True)),
                ("row_num", models.IntegerField(blank=True, null=True)),
                ("lectura_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": 'smart_med"."final_hechos',
                "managed": False,
            },
        ),
    ]
