# Generated by Django 4.1 on 2025-05-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiSmart", "0007_finalhechos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meterdata",
            fields=[
                (
                    "meter_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("costumer", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
            ],
            options={
                "db_table": 'smart_med"."final_meterdata',
                "managed": False,
            },
        ),
    ]
